// Typelizer digest 71066d266c05c0b72b2dc3048155521e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Pagy = {
  page: number;
  pages: number;
  count: number;
  limit: number;
  from: number;
  to: number;
  previous: number | null;
  next: number | null;
}

export type { Pagy };
