// Typelizer digest d416798f4473ca0ff34b6c53701ad14d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Session = {
  id: number;
}

type SessionDetailsTrait = {
  user_agent: string | null;
  ip_address: string | null;
  created_at: string;
}

export type { Session, SessionDetailsTrait };
