// Typelizer digest 91aae3b122e78e510f5d8731ace36257
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Session = {
  id: number;
}

type SessionDetailsTrait = {
  user_agent: string | null;
  ip_address: string | null;
  created_at: string;
  can_destroy: boolean;
}

export type { Session, SessionDetailsTrait };
