// Typelizer digest 4bc7372b3c08122f7c58ebeda26a3a0c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Session, SessionDetailsTrait} from '@/types'

type SettingsSessionsIndex = {
  sessions: Array<Session & SessionDetailsTrait>;
}

export type { SettingsSessionsIndex };
