// Typelizer digest a2b07ac1f9f8528aa6750c1f46ec73bd
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Session, Pagy, SessionDetailsTrait} from '@/types'

type SettingsSessionsIndex = {
  sessions: Array<Session & SessionDetailsTrait>;
  pagy: Pagy;
  sort_key: string;
  sort_direction: 'asc' | 'desc';
}

export type { SettingsSessionsIndex };
