// Typelizer digest b3af2469e67bb829f04a61b8f45ace59
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Auth} from '@/types'

type SharedProps = {
  auth: Auth;
  appearance: 'light' | 'dark' | 'system';
}

export type { SharedProps };
