// Typelizer digest e86b0ee669ff24b4fd503df90b1c9e3d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  name: string;
  email: string;
  verified: boolean;
  created_at: string;
  updated_at: string;
}

export type { User };
