// Typelizer digest d681840390f201c2172204841c60b7ae
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  name: string;
  email: string;
  verified: boolean;
  created_at: string;
  updated_at: string;
  avatar_url: string | null;
}

export type { User };
